const NB_TEST_USERS = 9;

const NB_TEST_BUDGET_PER_USER = 4;
const NB_TEST_BUDGET_WITH_CHILD_PER_USER = 2;

const NB_TEST_CATEGORY_PER_BUDGET = 4;
const NB_TEST_CATEGORY_WITH_CHILD_PER_BUDGET = 2;

const NB_TEST_LINE_PER_CATEGORY = 4;
const NB_TEST_LINE_WITH_CHILD_PER_CATEGORY = 2;

const NB_TEST_ENTRY_PER_LINE = 4;
const NB_TEST_ENTRY_WITH_CHILD_PER_LINE = 2;

module.exports = {
    NB_TEST_USERS: NB_TEST_USERS,

    NB_TEST_BUDGET_PER_USER : NB_TEST_BUDGET_PER_USER,
    NB_TEST_BUDGET_WITH_CHILD_PER_USER: NB_TEST_BUDGET_WITH_CHILD_PER_USER,

    NB_TEST_CATEGORY_PER_BUDGET: NB_TEST_CATEGORY_PER_BUDGET,
    NB_TEST_CATEGORY_WITH_CHILD_PER_BUDGET: NB_TEST_CATEGORY_WITH_CHILD_PER_BUDGET,

    NB_TEST_LINE_PER_CATEGORY: NB_TEST_LINE_PER_CATEGORY,
    NB_TEST_LINE_WITH_CHILD_PER_CATEGORY: NB_TEST_LINE_WITH_CHILD_PER_CATEGORY,

    NB_TEST_ENTRY_PER_LINE: NB_TEST_ENTRY_PER_LINE,
    NB_TEST_ENTRY_WITH_CHILD_PER_LINE: NB_TEST_ENTRY_WITH_CHILD_PER_LINE
}